### ISSUE TITLE
Update the webinterface

### ISSUE THREAD

**Issue by Creepsky** [Creepsky/creepMiner#75]
## informations

The webserver shows so far only found, sent and confirmed nonces and some other infos.
It should show

- [x] all system informations
- [x] target deadline
- [x] all log messages
  - [x] all types except ```information``` (every information gets an own json object)
- [ ] the verification process

## features

- [ ] Shutdown should be safed with an admin password
- [x] possibility to view, change and reparse the config
- [x] view all plot files + dirs
- [ ] Safe the whole webinterface with an user password

**Comment by Pascal66** [comment]
So it acting like an chidrenpool of a pool ?

**Comment by Creepsky** [comment]
A little bit ;) but the main idea is a nice front-end for the miner where you can view the status and change settings and so on.

**Comment by Pascal66** [comment]
As long as you agregate status of miners,(a thread is one of us) you are working as pool no ?
So. If you mix all of miners, you loose all the fees for the 'parent' pool from this deadline.
Because you are sending only the last DL from your pool, instead of receiving a sharing from the 'parent' .
IE : diskA,B,D from one computer
diskC had the BestDL 

If you submit directly to a pool the BestDL from DiskC, you win (if it win the block) x Burst
If you submit BestDL from disk A,B,D, you loose this BestDeadLine from the 'Parent' of mining. (wich can win a block in the same time, but you server didnt know that)

Never forget, that you can 'Win' Fees (As long as the burstPoolServer do that) only, and ONLY if you pool win a block. So how you can give Burst to your 'ChidrenPool' ?

**Comment by Creepsky** [comment]
What have this to do with the webserver? Or the creepMiner? Seems like you posted it in the wrong repository?

**Comment by Pascal66** [comment]
Hey.. Jsut giving my experience..
 
Clear in my mind, but not for others sorry :)

**Comment by Pascal66** [comment]
Close it.

**Comment by Creepsky** [comment]
If anyone reads this, has javascript/html skills and wants to enhance and optimize the web-interface, please don't hesitate to contact me :+1:

**Comment by hheexx** [comment]
Hi @Creepsky ,
I can spend few hours per week if still needed.
